/**
 * Fight API
 * This API allows a hero and a villain to fight
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import {EventEmitter, Inject, Injectable, Optional, Output} from '@angular/core';
import {HttpClient, HttpEvent, HttpHeaders, HttpResponse} from '@angular/common/http';

import {Observable} from 'rxjs';

import {Tarjeta} from '../model/tarjeta';
import {ModelLong} from '../model/modelLong';
import {ModelString} from '../model/modelString';
import {URI} from '../model/uRI';

import {BASE_PATH} from '../variables';
import {Configuration} from '../configuration';


@Injectable()
export class TarjetaService {

  protected basePath = 'http://localhost:8083';
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();

  @Output() emitter = new EventEmitter<Tarjeta>();

  constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
    if (basePath) {
      this.basePath = basePath;
    }
    if (!window.location.host.includes("localhost")) {
      this.basePath = window.location.protocol + "//" + window.location.host;
    }

    if (configuration) {
      this.configuration = configuration;
      this.basePath = basePath || configuration.basePath || this.basePath;
    }
  }

  /**
   * @param consumes string[] mime-types
   * @return true: consumes contains 'multipart/form-data', false: otherwise
   */
  private canConsumeForm(consumes: string[]): boolean {
    const form = 'multipart/form-data';
    for (const consume of consumes) {
      if (form === consume) {
        return true;
      }
    }
    return false;
  }


  /**
   * Returns all the tarjetas from the database
   *
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  // tag::adocService[]
  public apiTarjetasGet(observe?: 'body', reportProgress?: boolean): Observable<Array<Tarjeta>>;
  public apiTarjetasGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Tarjeta>>>;
  public apiTarjetasGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Tarjeta>>>;

  // end::adocService[]
  public apiTarjetasGet(observe: any = 'body', reportProgress: boolean = false): Observable<any> {

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      'application/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.get<Array<Tarjeta>>(`${this.basePath}/api/tarjetas`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   *
   *
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public apiHelloGet(observe?: 'body', reportProgress?: boolean): Observable<ModelString>;
  public apiHelloGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ModelString>>;
  public apiHelloGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ModelString>>;
  public apiHelloGet(observe: any = 'body', reportProgress: boolean = false): Observable<any> {

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      'text/plain'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.get<ModelString>(`${this.basePath}/api/tarjetas/hello`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }
}
